= kakoune-mblaze

This plugin integrates the https://git.vuxu.org/mblaze/[mblaze] suite of Unix
utilities for dealing with Maildir into the https://kakoune.org[Kakoune] editor (version `v2024.05.09` or higher).

== Installation

[source,shell]
----
git clone https://github.com/krobelus/kakoune-mblaze \
    ~/.config/kak/autoload/kakoune-mblaze
kak -e 'doc mblaze'
----

== Usage

=== Listing and showing messages

`mblaze-scan` pipes the output of the given shell script into `mscan` and
shows the result in an `\*mblaze-scan*` buffer.
Example:

[source,kak]
----
mblaze-scan %{mlist $(mdirs) | mthread}
----

Inside `\*mblaze-scan*`, you can run

* `mblaze-show` to show selected messages in an `\*mblaze-show*` buffer
* `mblaze-refresh` to update the scan buffer by re-running its command
* `mblaze-next-thread` or `mblaze-previous-thread` to move the main cursor to the next or previous thread start

=== Current message(s)

Most `mblaze-*` commands operate on the "current message(s)", which is defined as follows:

* in an `\*mblaze-scan*` buffer, the messages covered by the selections.
  Commands that operate on only one message only consider the main cursor.
* in an `\*mblaze-show*` buffer, the messages shown.
  Commands that operate on only one message currently fail in show buffers
  where multiple messages are shown.

=== Auto-rendering the current message

To show the <<current-message(s),current message>> in another client as you
browse the scan buffer, set `mblaze_autoshow_client`.  For example:

[source,kak]
----
mblaze-scan %{ mlist $(mdirs) | mthread }
new evaluate-commands %{ set-option global mblaze_autoshow_client %val{client} }
----

=== Operating on messages

`mblaze-pipe-to <command>` writes the <<current-message(s),current messages>>
to the command via standard input, one filename per line, and then calls
`mblaze-refresh` if called from a scan buffer.
The command's output is currently shown in the `\*debug*` buffer.
For example:

[source,kak]
----
mblaze-pipe-to %{ mrefile "$(mhdr -h maildir ~/.mblaze/profile)"/archive }
----

For this `mrefile` use case, there is a convenience wrapper `mblaze-refile <maildir_folder>`.

In a scan buffer, `mblaze-pipe-to` and `mblaze-refile` support the `-thread`
argument, to pipe the whole threads as listed in the scan buffer.

=== Writing messages

`mblaze-compose` wraps `mcom(1)` to create a draft message and edits it.

`mblaze-reply` and `mblaze-forward` wrap `mrep(1)` and `mfwd(1)` to create and
edit a draft reply to or forward of the <<current-message(s),current message>>.

`mblaze-send` sends the message draft in the current buffer with `mcom -send`.

=== MIME parts

`mblaze-open-named-mime-parts <part_filename>...` opens the given named MIME
parts (such as attachments) from the current message.

`mblaze-open-html-mime-part` opens the unique unnamed `text/html` part of the
current message. It fails if the message has no such part or has multiple
unnamed `text/html` parts.

Both commands call `mblaze-open-mime-part <message_file> <part> <mime_type>`
which needs to be overridden by the user.  For example, to save MIME parts
in the current directory and open them, do:

[source,kak]
----
define-command -override mblaze-open-mime-part -params 3 %{
    nop %sh{
        message_file=$1 part=$2 mime_type=$3
        mshow -n -x "$message_file" "$part"
        xdg-open "$part"
    }
}
----

== Example mappings

Search for occurrences of `mblaze` in https://git.sr.ht/~krobelus/dotfiles/tree/master/item/.config/kak/kakrc[my kakrc].

== History

I was previously using https://git.sr.ht/~parasrah/mblaze.kak for some of
my workflows; when I finally got around to writing this plugin and using it
for all my mail, I based it on https://github.com/mawww/mblaze.kak because
that had fewer things I needed to change.

== Status

This plugin is fairly new, so some behavior changes are expected.

== Contributing

Send feedback and patches to
mailto:\~krobelus/kakoune@lists.sr.ht[~krobelus/kakoune@lists.sr.ht] (see
https://lists.sr.ht/\~krobelus/kakoune[public archives]) or use GitHub.
