#!/bin/sh

set -e

[ "$1" = kak_command_fifo ]
[ "$2" = kak_response_fifo ]
selections_desc=$3

echo "echo -to-file $kak_response_fifo -quoting shell -- %opt{mblaze_shown_files}" >"$kak_command_fifo"
eval "set -- $(cat "$kak_response_fifo")"
if [ "$#" -ne 0 ]; then
    mseq -f -- "$@"
else
    "${kak_opt_mblaze_source%/*}"/mblaze-list-files \
        kak_command_fifo kak_response_fifo "$selections_desc"
fi
